spring.application.name=hotel-microservice

server.port=8083


#Mysql connectivity
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_microservice?createDatabaseIfNotExist=true&autoReconnect=true&userSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrivel=true&useUnicode=true&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver


#JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true





